steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/slashmcp/mcp-registry/mcp-registry-backend:$COMMIT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/slashmcp/mcp-registry/mcp-registry-backend:latest'
      - '-f'
      - 'backend/Dockerfile'
      - 'backend/'
    timeout: 1200s

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/slashmcp/mcp-registry/mcp-registry-backend:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mcp-registry-backend'
      - '--image'
      - 'us-central1-docker.pkg.dev/slashmcp/mcp-registry/mcp-registry-backend:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'

images:
  - 'us-central1-docker.pkg.dev/slashmcp/mcp-registry/mcp-registry-backend:latest'

timeout: 2400s

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
