steps:
  # Build the container image using Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mcp-registry-backend:$BUILD_ID', '-f', 'Dockerfile', '.']

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mcp-registry-backend:$BUILD_ID']

images:
  - 'gcr.io/$PROJECT_ID/mcp-registry-backend:$BUILD_ID'
